<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYbaaACS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYbaaACS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYbaaACS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYbaaACS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYbaaACS\App_KernelDevDebugContainer([
    'container.build_hash' => 'YbaaACS',
    'container.build_id' => '8e3c4066',
    'container.build_time' => 1641184536,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYbaaACS');
