<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYfAEAC0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYfAEAC0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYfAEAC0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYfAEAC0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYfAEAC0\App_KernelDevDebugContainer([
    'container.build_hash' => 'YfAEAC0',
    'container.build_id' => 'a0c91a0a',
    'container.build_time' => 1640576544,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYfAEAC0');
